### ISSUE TITLE
SVG on Firefox.

### ISSUE THREAD

**Issue by michelecocuccio** [jackmoore/zoom#56]
First of all, thanks for this fantastic jQuery zoom!
The only problem that i've got is that on Firefox if I use a SVG picture it doesn't work :(.

Is there any fix for this?

**Comment by Eric-Jackson** [comment]
I managed to get it working by using the following:

``` css
.zoomImg {
  min-height: 1500px !important;
  width: auto !important;
}
```

This isn't anywhere near the correct solution but hopefully this helps the dev find a good solution.
